### ISSUE TITLE
Best silent miner

### ISSUE THREAD

**Issue by Flantn** [operationalguy/silent-XMRig-miner#4]
Hello, I’m looking for the best silent miner. I have access to the computers, but antivirus programs detect the software. Is there another method where I could install different malware that isn’t visible?

**Comment by operationalguy** [comment]
@Flantn Please read readme.md really well next time, it clearly says "This software's main purpose is NOT to be used maliciously, or on any system that you do not own, or have the right to use.". So I will not be helping you.
Have a nice day!
