### ISSUE TITLE
how to update, uninstall or check?

### ISSUE THREAD

**Issue by macmac1121** [operationalguy/silent-XMRig-miner#8]
Let's say I want to update the configuration, should I just build it and install it on the target machine? 
Is it better to first run something that uninstalls the current miner and then install the new one?

additionally, is there a way to check the current miner configs in the target machine to check if the configs are updated properly.

Thanks and Regards.

**Comment by operationalguy** [comment]
Hi @macmac1121 
1. Now there is no way to update the configuration, but we are working to add this functionality.
2. There is no uninstaller.
3. You will not be able to install a miner again on the machine that already has one installed. So we suggest to use fresh VM.
4. There is no way to check the current configuration

You are welcome.

**Comment by macmac1121** [comment]
Alright, thanks
closing this
